spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spot_db?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: spot
    password: spot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: teamspotversion3
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
    username: team.spot.v3@gmail.com


