package com.example.spot.common.words;

import java.util.Arrays;

public class CheckWordList {

   public static boolean badWordsConfirm(String nickname) {
      return Arrays.stream(BAD_WORDS).anyMatch(word -> nickname.contains(word));
   }

   private static final String[] BAD_WORDS = {
           "10새","10새기","10새리","10세리","10쉐이","10쉑","10스","10쌔"," 10쌔기",
           "10쎄","10알","10창","10탱","18것","18넘","18년","18노","18놈","18뇬",
           "18럼","18롬","18새","18새끼","18색","18세끼","18세리","18섹","18쉑",
           "18스","18아","ㄱㅐ","ㄲㅏ","ㄲㅑ","ㄲㅣ","ㅅㅂㄹㅁ","ㅅㅐ","ㅆㅂㄹㅁ","ㅆㅍ",
           "ㅆㅣ","ㅆ앙","ㅍㅏ","凸"," 갈보","갈보년","강아지","같은년","같은뇬","개같은",
           "개구라","개년","개놈","개뇬","개대중","개독","개돼중","개랄","개보지","개뻥",
           "개뿔","개새","개새기","개새끼","개새키","개색기","개색끼","개색키","개색히",
           "개섀끼","개세","개세끼","개세이","개소리","개쑈"," 개쇳기","개수작","개쉐",
           "개쉐리","개쉐이","개쉑","개쉽","개스끼","개시키","개십새기"," 개십새끼","개q",
           "개씹","개아들","개자슥","개자지","개접","개좆","개좌식","개허접","걔새","걔수작",
           "걔시끼","걔시키","걔y","걸레","게색기","게색끼","광뇬","구녕","구라","구멍",
           "그년","그새끼","냄비","놈현","뇬","눈깔","뉘미럴","니귀미","니기미","니미",
           "니미랄","니미럴","니미씹","니아배","니아베","니아비","니어매","니어메","니어미",
           "닝기리","닝기미","대가리","뎡신","도라이","돈놈","돌아이","돌은놈","되질래","뒈져",
           "뒈져라","뒈진","뒈진다","뒈질"," 뒤질래","등신","디져라","디진다","디질래","딩시",
           "따식","때놈","또라이","똘아이","똘아이","뙈놈","뙤놈","뙨넘","뙨놈","뚜쟁","띠바",
           "띠발","띠불","띠팔","메친넘","메친놈","미췬"," 미췬","미친","미친넘","미친년","미친놈",
           "미친새끼","미친스까이","미틴","미틴넘","미틴년"," 미틴놈","바랄년","병자","뱅마","뱅신",
           "벼엉신","병쉰","병신","부랄","부럴","불알","불할","붕가","붙어먹","뷰웅","븅","븅신",
           "빌어먹","빙시","빙신","빠가","빠구리","빠굴","빠큐","뻐큐","뻑큐","뽁큐","상넘이","상놈을",
           "상놈의","상놈이","새갸","새꺄","새끼","새새끼","새키","색끼","생쑈","세갸","세꺄","세끼","섹스",
           "쇼하네","쉐","쉐기","쉐끼","쉐리","쉐에기","쉐키","쉑","x","–","쉬발","쉬밸","쉬벌","쉬뻘",
           "쉬펄","쉽알","스패킹","스팽","시궁창","시끼","시댕","시뎅","시랄","시발","시벌","시부랄","시부럴",
           "시부리","시불","시브랄","시팍","시팔","시펄","신발끈","심발끈","심탱","십8","십라","십새","십새끼",
           "십세","십쉐","십쉐이","십스키","십쌔","십창","십탱","싶알","싸가지","싹아지","쌉년","쌍넘","쌍년","쌍놈",
           "쌍뇬","쌔끼"," 쌕","쌩쑈","b년","썅","썅년","썅놈","쇼","써벌","썩을년","썩을놈","쎄꺄","쎄엑",
           "쒸벌","쒸뻘","쒸팔","쒸펄","쓰바","쓰박","쓰발","쓰벌","쓰팔","씁새","씁얼","씌파","씨8"," 씨끼","씨댕",
           "씨뎅","씨바","씨바랄","씨박","씨발","씨방","씨방새","씨방세","씨밸","씨뱅","씨벌","씨벨","씨봉","씨봉알",
           "씨부랄","씨부럴","씨부렁","씨부리","씨불","씨붕","씨브랄"," 씨빠","씨빨","씨뽀랄","씨앙","씨파","씨팍",
           "씨팔","씨펄","씸년","씸뇬","씸새끼","씹같","씹년","씹뇬","씹보지","씹새","씹새기","씹새끼","씹새리",
           "씹세","씹쉐","씹스키","씹쌔","씹이","씹자지","씹질","씹창","씹탱","씹�","씹팔","씹할","씹헐","아가리",
           "아갈","아갈이","아갈통","아구창","아구통","아굴","얌마","양넘","양년","양놈","엄창","엠병","여물통","염병",
           "엿같","옘병","옘빙","오입","왜년","왜놈","욤병","육갑","은년","을년","이년","이새끼","이새키","이스끼",
           "이스키","임마","자슥","잡것","잡넘","잡년","잡놈","저년","저새끼","접년","젖밥","조까","조까치","조낸","조또","조랭",
           "조빠","조쟁이","조지냐","조진다","조찐","  조질래","존나","존나게","존니","존만"," 존만한","좀물","좁년","좆","좁밥","좃까",
           "좃또","좃만","좃밥","좃이","좃찐","좆같","좆까","좆나","좆또","좆만","좆밥","좆이","좆찐","좇같","좇이","좌식","주글","주글래",
           "주데이","주뎅","주뎅이","주둥아리","주둥이","주접","주접떨","죽고잡","죽을래","죽통","쥐랄","쥐롤","쥬디","지랄","지럴","지롤","지미랄",
           "짜식","짜아식","쪼다","쫍빱","찌랄","창녀","캐년","캐놈","캐스끼","캐스키","캐시키","탱구","팔럼","퍽큐","호로","호로놈","호로새끼","호로색",
           "호로쉑","호로스까이","호로스키","후라들","후래자식","후레","후뢰","씨ㅋ발","ㅆ1발","씌발","띠발","띄발","뛰발","띠ㅋ발","뉘뮈",
           "2g1c",
           "4r5e",
           "5h1t",
           "5hit",
           "a$$",
           "a$$hole",
           "a_s_s",
           "a2m",
           "a54",
           "a55",
           "a55hole",
           "aeolus",
           "ahole",
           "alabama hot pocket",
           "alaskan pipeline",
           "anal",
           "anal impaler",
           "anal leakage",
           "analannie",
           "analprobe",
           "analsex",
           "anilingus",
           "anus",
           "apeshit",
           "ar5e",
           "areola",
           "areole",
           "arian",
           "arrse",
           "arse",
           "arsehole",
           "aryan",
           "ass",
           "ass fuck",
           "ass hole",
           "assault",
           "assbag",
           "assbagger",
           "assbandit",
           "assbang",
           "assbanged",
           "assbanger",
           "assbangs",
           "assbite",
           "assblaster",
           "assclown",
           "asscock",
           "asscracker",
           "asses",
           "assface",
           "assfaces",
           "assfuck",
           "assfucker",
           "ass-fucker",
           "assfukka",
           "assgoblin",
           "assh0le",
           "asshat",
           "ass-hat",
           "asshead",
           "assho1e",
           "asshole",
           "assholes",
           "asshopper",
           "asshore",
           "ass-jabber",
           "assjacker",
           "assjockey",
           "asskiss",
           "asskisser",
           "assklown",
           "asslick",
           "asslicker",
           "asslover",
           "assman",
           "assmaster",
           "assmonkey",
           "assmucus",
           "assmunch",
           "assmuncher",
           "assnigger",
           "asspacker",
           "asspirate",
           "ass-pirate",
           "asspuppies",
           "assranger",
           "assshit",
           "assshole",
           "asssucker",
           "asswad",
           "asswhole",
           "asswhore",
           "asswipe",
           "asswipes",
           "auto erotic",
           "autoerotic",
           "axwound",
           "azazel",
           "azz",
           "b!tch",
           "b00bs",
           "b17ch",
           "b1tch",
           "babe",
           "babeland",
           "babes",
           "baby batter",
           "baby juice",
           "badfuck",
           "ball gag",
           "ball gravy",
           "ball kicking",
           "ball licking",
           "ball sack",
           "ball sucking",
           "ballbag",
           "balllicker",
           "balls",
           "ballsack",
           "bampot",
           "bang",
           "bangbros",
           "banger",
           "banging",
           "bareback",
           "barely legal",
           "barenaked",
           "barf",
           "barface",
           "barfface",
           "bastard",
           "bastardo",
           "bastards",
           "bastinado",
           "batty boy",
           "bawdy",
           "bazongas",
           "bazooms",
           "bbw",
           "bdsm",
           "beaner",
           "beaners",
           "beardedclam",
           "beastial",
           "beastiality",
           "beatch",
           "beater",
           "beatyourmeat",
           "beaver",
           "beaver cleaver",
           "beaver lips",
           "beef curtain",
           "beef curtains",
           "beer",
           "beeyotch",
           "bellend",
           "bender",
           "beotch",
           "bestial",
           "bestiality",
           "bi+ch",
           "biatch",
           "bicurious",
           "big black",
           "big breasts",
           "big knockers",
           "big tits",
           "bigbastard",
           "bigbutt",
           "bigger",
           "bigtits",
           "bimbo",
           "bimbos",
           "bint",
           "birdlock",
           "bisexual",
           "bi-sexual",
           "bitch",
           "bitch tit",
           "bitchass",
           "bitched",
           "bitcher",
           "bitchers",
           "bitches",
           "bitchez",
           "bitchin",
           "bitching",
           "bitchtits",
           "bitchy",
           "black cock",
           "blonde action",
           "blonde on blonde action",
           "bloodclaat",
           "bloody",
           "bloody hell",
           "blow",
           "blow job",
           "blow me",
           "blow mud",
           "blow your load",
           "blowjob",
           "blowjobs",
           "blue waffle",
           "blumpkin",
           "boang",
           "bod",
           "bodily",
           "bogan",
           "bohunk",
           "boink",
           "boiolas",
           "bollick",
           "bollock",
           "bollocks",
           "bollok",
           "bollox",
           "bomd",
           "bondage",
           "bone",
           "boned",
           "boner",
           "boners",
           "bong",
           "boob",
           "boobies",
           "boobs",
           "booby",
           "booger",
           "bookie",
           "boong",
           "boonga",
           "booobs",
           "boooobs",
           "booooobs",
           "booooooobs",
           "bootee",
           "bootie",
           "booty",
           "booty call",
           "booze",
           "boozer",
           "boozy",
           "bosom",
           "bosomy",
           "bowel",
           "bowels",
           "bra",
           "brassiere",
           "breast",
           "breastjob",
           "breastlover",
           "breastman",
           "breasts",
           "breeder",
           "brotherfucker",
           "brown showers",
           "brunette action",
           "buceta",
           "bugger",
           "buggered",
           "buggery",
           "bukkake",
           "bull shit",
           "bullcrap",
           "bulldike",
           "bulldyke",
           "bullet vibe",
           "bullshit",
           "bullshits",
           "bullshitted",
           "bullturds",
           "bum",
           "bum boy",
           "bumblefuck",
           "bumclat",
           "bumfuck",
           "bummer",
           "bung",
           "bung hole",
           "bunga",
           "bunghole",
           "bunny fucker",
           "bust a load",
           "busty",
           "butchdike",
           "butchdyke",
           "butt",
           "butt fuck",
           "butt plug",
           "buttbang",
           "butt-bang",
           "buttcheeks",
           "buttface",
           "buttfuck",
           "butt-fuck",
           "buttfucka",
           "buttfucker",
           "butt-fucker",
           "butthead",
           "butthole",
           "buttman",
           "buttmuch",
           "buttmunch",
           "buttmuncher",
           "butt-pirate",
           "buttplug",
           "c.0.c.k",
           "c.o.c.k.",
           "c.u.n.t",
           "c0ck",
           "c-0-c-k",
           "c0cksucker",
           "caca",
           "cahone",
           "camel toe",
           "cameltoe",
           "camgirl",
           "camslut",
           "camwhore",
           "carpet muncher",
           "carpetmuncher",
           "cawk",
           "cervix",
           "chesticle",
           "chi-chi man",
           "chick with a dick",
           "child-fucker",
           "chin",
           "chinc",
           "chincs",
           "chink",
           "chinky",
           "choad",
           "choade",
           "choc ice",
           "chocolate rosebuds",
           "chode",
           "chodes",
           "chota bags",
           "cipa",
           "circlejerk",
           "cl1t",
           "cleveland steamer",
           "climax",
           "clit",
           "clit licker",
           "clitface",
           "clitfuck",
           "clitoris",
           "clitorus",
           "clits",
           "clitty",
           "clitty litter",
           "clogwog",
           "clover clamps",
           "clunge",
           "clusterfuck",
           "cnut",
           "cocain",
           "cocaine",
           "cock",
           "c-o-c-k",
           "cock pocket",
           "cock snot",
           "cock sucker",
           "cockass",
           "cockbite",
           "cockblock",
           "cockburger",
           "cockeye",
           "cockface",
           "cockfucker",
           "cockhead",
           "cockholster",
           "cockjockey",
           "cockknocker",
           "cockknoker",
           "cocklicker",
           "cocklover",
           "cocklump",
           "cockmaster",
           "cockmongler",
           "cockmongruel",
           "cockmonkey",
           "cockmunch",
           "cockmuncher",
           "cocknose",
           "cocknugget",
           "cocks",
           "cockshit",
           "cocksmith",
           "cocksmoke",
           "cocksmoker",
           "cocksniffer",
           "cocksucer",
           "cocksuck",
           "cocksuck ",
           "cocksucked",
           "cocksucker",
           "cock-sucker",
           "cocksuckers",
           "cocksucking",
           "cocksucks",
           "cocksuka",
           "cocksukka",
           "cockwaffle",
           "coffin dodger",
           "coital",
           "cok",
           "cokmuncher",
           "coksucka",
           "commie",
           "condom",
           "coochie",
           "coochy",
           "coon",
           "coonnass",
           "coons",
           "cooter",
           "cop some wood",
           "coprolagnia",
           "coprophilia",
           "corksucker",
           "cornhole",
           "corp whore",
           "cox",
           "crabs",
           "crack",
           "cracker",
           "crackwhore",
           "crack-whore",
           "crap",
           "crappy",
           "creampie",
           "cretin",
           "crikey",
           "cripple",
           "crotte",
           "cum",
           "cum chugger",
           "cum dumpster",
           "cum freak",
           "cum guzzler",
           "cumbubble",
           "cumdump",
           "cumdumpster",
           "cumguzzler",
           "cumjockey",
           "cummer",
           "cummin",
           "cumming",
           "cums",
           "cumshot",
           "cumshots",
           "cumslut",
           "cumstain",
           "cumtart",
           "cunilingus",
           "cunillingus",
           "cunn",
           "cunnie",
           "cunnilingus",
           "cunntt",
           "cunny",
           "cunt",
           "c-u-n-t",
           "cunt hair",
           "cuntass",
           "cuntbag",
           "cuntface",
           "cuntfuck",
           "cuntfucker",
           "cunthole",
           "cunthunter",
           "cuntlick",
           "cuntlick ",
           "cuntlicker",
           "cuntlicker ",
           "cuntlicking",
           "cuntrag",
           "cunts",
           "cuntsicle",
           "cuntslut",
           "cunt-struck",
           "cuntsucker",
           "cut rope",
           "cyalis",
           "cyberfuc",
           "cyberfuck",
           "cyberfucked",
           "cyberfucker",
           "cyberfuckers",
           "cyberfucking",
           "cybersex",
           "d0ng",
           "d0uch3",
           "d0uche",
           "d1ck",
           "d1ld0",
           "d1ldo",
           "dago",
           "dagos",
           "dammit",
           "damn",
           "damned",
           "damnit",
           "darkie",
           "darn",
           "date rape",
           "daterape",
           "dawgie-style",
           "deep throat",
           "deepthroat",
           "deggo",
           "dendrophilia",
           "dick",
           "dick head",
           "dick hole",
           "dick shy",
           "dickbag",
           "dickbeaters",
           "dickbrain",
           "dickdipper",
           "dickface",
           "dickflipper",
           "dickfuck",
           "dickfucker",
           "dickhead",
           "dickheads",
           "dickhole",
           "dickish",
           "dick-ish",
           "dickjuice",
           "dickmilk",
           "dickmonger",
           "dickripper",
           "dicks",
           "dicksipper",
           "dickslap",
           "dick-sneeze",
           "dicksucker",
           "dicksucking",
           "dicktickler",
           "dickwad",
           "dickweasel",
           "dickweed",
           "dickwhipper",
           "dickwod",
           "dickzipper",
           "diddle",
           "dike",
           "dildo",
           "dildos",
           "diligaf",
           "dillweed",
           "dimwit",
           "dingle",
           "dingleberries",
           "dingleberry",
           "dink",
           "dinks",
           "dipship",
           "dipshit",
           "dirsa",
           "dirty",
           "dirty pillows",
           "dirty sanchez",
           "dlck",
           "dog style",
           "dog-fucker",
           "doggie style",
           "doggiestyle",
           "doggie-style",
           "doggin",
           "dogging",
           "doggy style",
           "doggystyle",
           "doggy-style",
           "dolcett",
           "domination",
           "dominatrix",
           "dommes",
           "dong",
           "donkey punch",
           "donkeypunch",
           "donkeyribber",
           "doochbag",
           "doofus",
           "dookie",
           "doosh",
           "dopey",
           "double dong",
           "double penetration",
           "doublelift",
           "douch3",
           "douche",
           "douchebag",
           "douchebags",
           "douche-fag",
           "douchewaffle",
           "douchey",
           "dp action",
           "drunk",
           "dry hump",
           "duche",
           "dumass",
           "dumb ass",
           "dumbass",
           "dumbasses",
           "dumbcunt",
           "dumbfuck",
           "dumbshit",
           "dummy",
           "dumshit",
           "dvda",
           "dyke",
           "dykes",
           "eat a dick",
           "eat hair pie",
           "eat my ass",
           "eatpussy",
           "ecchi",
           "ejaculate",
           "ejaculated",
           "ejaculates",
           "ejaculating",
           "ejaculatings",
           "ejaculation",
           "ejakulate",
           "enlargement",
           "erect",
           "erection",
           "erotic",
           "erotism",
           "escort",
           "essohbee",
           "eunuch",
           "extacy",
           "extasy",
           "f u c k",
           "f u c k e r",
           "f.u.c.k",
           "f_u_c_k",
           "f4nny",
           "facefucker",
           "facial",
           "fack",
           "fag",
           "fagbag",
           "fagfucker",
           "fagg",
           "fagged",
           "fagging",
           "faggit",
           "faggitt",
           "faggot",
           "faggotcock",
           "faggots",
           "faggs",
           "fagot",
           "fagots",
           "fags",
           "fagtard",
           "faig",
           "faigt",
           "fanny",
           "fannybandit",
           "fannyflaps",
           "fannyfucker",
           "fanyy",
           "fart",
           "fartknocker",
           "fastfuck",
           "fat",
           "fatass",
           "fatfuck",
           "fatfucker",
           "fcuk",
           "fcuker",
           "fcuking",
           "fecal",
           "feck",
           "fecker",
           "felch",
           "felcher",
           "felching",
           "fellate",
           "fellatio",
           "feltch",
           "feltcher",
           "female squirting",
           "femdom",
           "fenian",
           "figging",
           "fingerbang",
           "fingerfuck",
           "fingerfuck ",
           "fingerfucked",
           "fingerfucker",
           "fingerfucker ",
           "fingerfuckers",
           "fingerfucking",
           "fingerfucks",
           "fingering",
           "fist fuck",
           "fisted",
           "fistfuck",
           "fistfucked",
           "fistfucker",
           "fistfucker ",
           "fistfuckers",
           "fistfucking",
           "fistfuckings",
           "fistfucks",
           "fisting",
           "fisty",
           "flamer",
           "flange",
           "flaps",
           "fleshflute",
           "flog the log",
           "floozy",
           "foad",
           "foah",
           "fondle",
           "foobar",
           "fook",
           "fooker",
           "foot fetish",
           "footfuck",
           "footfucker",
           "footjob",
           "footlicker",
           "foreskin",
           "freakfuck",
           "freakyfucker",
           "freefuck",
           "freex",
           "frigg",
           "frigga",
           "frotting",
           "fubar",
           "fuc",
           "fuck",
           "f-u-c-k",
           "fuck buttons",
           "fuck hole",
           "fuck off",
           "fuck puppet",
           "fuck trophy",
           "fuck yo mama",
           "fuck you",
           "fucka",
           "fuckass",
           "fuck-ass",
           "fuckbag",
           "fuck-bitch",
           "fuckboy",
           "fuckbrain",
           "fuckbutt",
           "fuckbutter",
           "fucked",
           "fuckedup",
           "fucker",
           "fuckers",
           "fuckersucker",
           "fuckface",
           "fuckfreak",
           "fuckhead",
           "fuckheads",
           "fuckher",
           "fuckhole",
           "fuckin",
           "fucking",
           "fuckingbitch",
           "fuckings",
           "fuckingshitmotherfucker",
           "fuckme",
           "fuckme ",
           "fuckmeat",
           "fuckmehard",
           "fuckmonkey",
           "fucknugget",
           "fucknut",
           "fucknutt",
           "fuckoff",
           "fucks",
           "fuckstick",
           "fucktard",
           "fuck-tard",
           "fucktards",
           "fucktart",
           "fucktoy",
           "fucktwat",
           "fuckup",
           "fuckwad",
           "fuckwhit",
           "fuckwhore",
           "fuckwit",
           "fuckwitt",
           "fuckyou",
           "fudge packer",
           "fudgepacker",
           "fudge-packer",
           "fuk",
           "fuker",
           "fukker",
           "fukkers",
           "fukkin",
           "fuks",
           "fukwhit",
           "fukwit",
           "fuq",
           "futanari",
           "fux",
           "fux0r",
           "fvck",
           "fxck",
           "gae",
           "gai",
           "gang bang",
           "gangbang",
           "gang-bang",
           "gangbanged",
           "gangbangs",
           "ganja",
           "gash",
           "gassy ass",
           "gay sex",
           "gayass",
           "gaybob",
           "gaydo",
           "gayfuck",
           "gayfuckist",
           "gaylord",
           "gays",
           "gaysex",
           "gaytard",
           "gaywad",
           "gender bender",
           "genitals",
           "gey",
           "gfy",
           "ghay",
           "ghey",
           "giant cock",
           "gigolo",
           "ginger",
           "gippo",
           "girl on",
           "girl on top",
           "girls gone wild",
           "git",
           "glans",
           "goatcx",
           "goatse",
           "god damn",
           "godamn",
           "godamnit",
           "goddam",
           "god-dam",
           "goddammit",
           "goddamn",
           "goddamned",
           "god-damned",
           "goddamnit",
           "goddamnmuthafucker",
           "godsdamn",
           "gokkun",
           "golden shower",
           "goldenshower",
           "golliwog",
           "gonad",
           "gonads",
           "gonorrehea",
           "goo girl",
           "gooch",
           "goodpoop",
           "gook",
           "gooks",
           "goregasm",
           "gotohell",
           "gringo",
           "grope",
           "group sex",
           "gspot",
           "g-spot",
           "gtfo",
           "guido",
           "guro",
           "h0m0",
           "h0mo",
           "ham flap",
           "hand job",
           "handjob",
           "hard core",
           "hard on",
           "hardcore",
           "hardcoresex",
           "he11",
           "headfuck",
           "hebe",
           "heeb",
           "hell",
           "hemp",
           "hentai",
           "heroin",
           "herp",
           "herpes",
           "herpy",
           "heshe",
           "he-she",
           "hitler",
           "hiv",
           "hoar",
           "hoare",
           "hobag",
           "hoe",
           "hoer",
           "holy shit",
           "hom0",
           "homey",
           "homo",
           "homodumbshit",
           "homoerotic",
           "homoey",
           "honkey",
           "honky",
           "hooch",
           "hookah",
           "hooker",
           "hoor",
           "hootch",
           "hooter",
           "hooters",
           "hore",
           "horniest",
           "horny",
           "hot carl",
           "hot chick",
           "hotpussy",
           "hotsex",
           "how to kill",
           "how to murdep",
           "how to murder",
           "huge fat",
           "hump",
           "humped",
           "humping",
           "hun",
           "hussy",
           "hymen",
           "iap",
           "iberian slap",
           "inbred",
           "incest",
           "injun",
           "intercourse",
           "j3rk0ff",
           "jack off",
           "jackass",
           "jackasses",
           "jackhole",
           "jackoff",
           "jack-off",
           "jaggi",
           "jagoff",
           "jail bait",
           "jailbait",
           "jap",
           "japs",
           "jelly donut",
           "jerk",
           "jerk off",
           "jerk0ff",
           "jerkass",
           "jerked",
           "jerkoff",
           "jerk-off",
           "jigaboo",
           "jiggaboo",
           "jiggerboo",
           "jism",
           "jiz",
           "jizm",
           "jizz",
           "jizzed",
           "jock",
           "juggs",
           "jungle bunny",
           "junglebunny",
           "junkie",
           "junky",
           "kafir",
           "kawk",
           "kike",
           "kikes",
           "kill",
           "kinbaku",
           "kinkster",
           "kinky",
           "kkk",
           "klan",
           "knob",
           "knob end",
           "knobbing",
           "knobead",
           "knobed",
           "knobend",
           "knobhead",
           "knobjocky",
           "knobjokey",
           "kock",
           "kondum",
           "kondums",
           "kooch",
           "kooches",
           "kootch",
           "kraut",
           "kum",
           "kummer",
           "kumming",
           "kums",
           "kunilingus",
           "kunja",
           "kunt",
           "kwif",
           "kyke",
           "l3i+ch",
           "l3itch",
           "labia",
           "lameass",
           "lardass",
           "leather restraint",
           "leather straight jacket",
           "lech",
           "lemon party",
           "leper",
           "lesbian",
           "lesbians",
           "lesbo",
           "lesbos",
           "lez",
           "lezbian",
           "lezbians",
           "lezbo",
           "lezbos",
           "lezza",
           "lezzie",
           "lezzies",
           "lezzy",
           "lmao",
           "lmfao",
           "loin",
           "loins",
           "lolita",
           "looney",
           "lovemaking",
           "lube",
           "lust",
           "lusting",
           "lusty",
           "m0f0",
           "m0fo",
           "m45terbate",
           "ma5terb8",
           "ma5terbate",
           "mafugly",
           "make me come",
           "male squirting",
           "mams",
           "masochist",
           "massa",
           "masterb8",
           "masterbat",
           "masterbat3",
           "masterbate",
           "master-bate",
           "masterbating",
           "masterbation",
           "masterbations",
           "masturbate",
           "masturbating",
           "masturbation",
           "maxi",
           "mcfagget",
           "menage a trois",
           "menses",
           "menstruate",
           "menstruation",
           "meth",
           "m-fucking",
           "mick",
           "middle finger",
           "midget",
           "milf",
           "minge",
           "minger",
           "missionary position",
           "mof0",
           "mofo",
           "mo-fo",
           "molest",
           "mong",
           "moo moo foo foo",
           "moolie",
           "moron",
           "mothafuck",
           "mothafucka",
           "mothafuckas",
           "mothafuckaz",
           "mothafucked",
           "mothafucker",
           "mothafuckers",
           "mothafuckin",
           "mothafucking",
           "mothafuckings",
           "mothafucks",
           "mother fucker",
           "motherfuck",
           "motherfucka",
           "motherfucked",
           "motherfucker",
           "motherfuckers",
           "motherfuckin",
           "motherfucking",
           "motherfuckings",
           "motherfuckka",
           "motherfucks",
           "mound of venus",
           "mr hands",
           "mtherfucker",
           "mthrfucker",
           "mthrfucking",
           "muff",
           "muff diver",
           "muff puff",
           "muffdiver",
           "muffdiving",
           "munging",
           "munter",
           "murder",
           "mutha",
           "muthafecker",
           "muthafuckaz",
           "muthafuckker",
           "muther",
           "mutherfucker",
           "mutherfucking",
           "muthrfucking",
           "n1gga",
           "n1gger",
           "nad",
           "nads",
           "naked",
           "nambla",
           "napalm",
           "nappy",
           "nawashi",
           "nazi",
           "nazism",
           "need the dick",
           "negro",
           "neonazi",
           "nig nog",
           "nigaboo",
           "nigg3r",
           "nigg4h",
           "nigga",
           "niggah",
           "niggas",
           "niggaz",
           "nigger",
           "niggers",
           "niggle",
           "niglet",
           "nig-nog",
           "nimphomania",
           "nimrod",
           "ninny",
           "nipple",
           "nipples",
           "nob",
           "nob jokey",
           "nobhead",
           "nobjocky",
           "nobjokey",
           "nonce",
           "nooky",
           "nsfw images",
           "nude",
           "nudity",
           "numbnuts",
           "nut butter",
           "nut sack",
           "nutsack",
           "nutter",
           "nympho",
           "nymphomania",
           "octopussy",
           "old bag",
           "omg",
           "omorashi",
           "one cup two girls",
           "one guy one jar",
           "opiate",
           "opium",
           "oral",
           "orally",
           "organ",
           "orgasim",
           "orgasims",
           "orgasm",
           "orgasmic",
           "orgasms",
           "orgies",
           "orgy",
           "ovary",
           "ovum",
           "ovums",
           "p.u.s.s.y.",
           "p0rn",
           "paddy",
           "paedophile",
           "paki",
           "panooch",
           "pansy",
           "pantie",
           "panties",
           "panty",
           "pastie",
           "pasty",
           "pawn",
           "pcp",
           "pecker",
           "peckerhead",
           "pedo",
           "pedobear",
           "pedophile",
           "pedophilia",
           "pedophiliac",
           "pee",
           "peepee",
           "pegging",
           "penetrate",
           "penetration",
           "penial",
           "penile",
           "penis",
           "penisbanger",
           "penisfucker",
           "penispuffer",
           "perversion",
           "peyote",
           "phalli",
           "phallic",
           "phone sex",
           "phonesex",
           "phuck",
           "phuk",
           "phuked",
           "phuking",
           "phukked",
           "phukking",
           "phuks",
           "phuq",
           "piece of shit",
           "pigfucker",
           "pikey",
           "pillowbiter",
           "pimp",
           "pimpis",
           "pinko",
           "piss",
           "piss off",
           "piss pig",
           "pissed",
           "pissed off",
           "pisser",
           "pissers",
           "pisses",
           "pissflaps",
           "pissin",
           "pissing",
           "pissoff",
           "piss-off",
           "pisspig",
           "playboy",
           "pleasure chest",
           "pms",
           "polack",
           "pole smoker",
           "polesmoker",
           "pollock",
           "ponyplay",
           "poof",
           "poon",
           "poonani",
           "poonany",
           "poontang",
           "poop",
           "poop chute",
           "poopchute",
           "poopuncher",
           "porch monkey",
           "porchmonkey",
           "porn",
           "porno",
           "pornography",
           "pornos",
           "pot",
           "potty",
           "prick",
           "pricks",
           "prickteaser",
           "prig",
           "prince albert piercing",
           "prod",
           "pron",
           "prostitute",
           "prude",
           "psycho",
           "pthc",
           "pube",
           "pubes",
           "pubic",
           "pubis",
           "punani",
           "punanny",
           "punany",
           "punkass",
           "punky",
           "punta",
           "puss",
           "pusse",
           "pussi",
           "pussies",
           "pussy",
           "pussy fart",
           "pussy palace",
           "pussylicking",
           "pussypounder",
           "pussys",
           "pust",
           "puto",
           "queaf",
           "queef",
           "queer",
           "queerbait",
           "queerhole",
           "queero",
           "queers",
           "quicky",
           "quim",
           "racy",
           "raghead",
           "raging boner",
           "rape",
           "raped",
           "raper",
           "rapey",
           "raping",
           "rapist",
           "raunch",
           "rectal",
           "rectum",
           "rectus",
           "reefer",
           "reetard",
           "reich",
           "renob",
           "retard",
           "retarded",
           "reverse cowgirl",
           "revue",
           "rimjaw",
           "rimjob",
           "rimming",
           "ritard",
           "rosy palm",
           "rosy palm and her 5 sisters",
           "rtard",
           "r-tard",
           "rubbish",
           "rum",
           "rump",
           "rumprammer",
           "ruski",
           "rusty trombone",
           "s hit",
           "s&m",
           "s.h.i.t.",
           "s.o.b.",
           "s_h_i_t",
           "s0b",
           "sadism",
           "sadist",
           "sambo",
           "sand nigger",
           "sandbar",
           "sandler",
           "sandnigger",
           "sanger",
           "santorum",
           "sausage queen",
           "scag",
           "scantily",
           "scat",
           "schizo",
           "schlong",
           "scissoring",
           "screw",
           "screwed",
           "screwing",
           "scroat",
           "scrog",
           "scrot",
           "scrote",
           "scrotum",
           "scrud",
           "scum",
           "seaman",
           "seamen",
           "seduce",
           "seks",
           "semen",
           "sex",
           "sexo",
           "sexual",
           "sexy",
           "sh!+",
           "sh!t",
           "sh1t",
           "s-h-1-t",
           "shag",
           "shagger",
           "shaggin",
           "shagging",
           "shamedame",
           "shaved beaver",
           "shaved pussy",
           "shemale",
           "shi+",
           "shibari",
           "shirt lifter",
           "shit",
           "s-h-i-t",
           "shit ass",
           "shit fucker",
           "shitass",
           "shitbag",
           "shitbagger",
           "shitblimp",
           "shitbrains",
           "shitbreath",
           "shitcanned",
           "shitcunt",
           "shitdick",
           "shite",
           "shiteater",
           "shited",
           "shitey",
           "shitface",
           "shitfaced",
           "shitfuck",
           "shitfull",
           "shithead",
           "shitheads",
           "shithole",
           "shithouse",
           "shiting",
           "shitings",
           "shits",
           "shitspitter",
           "shitstain",
           "shitt",
           "shitted",
           "shitter",
           "shitters",
           "shittier",
           "shittiest",
           "shitting",
           "shittings",
           "shitty",
           "shiz",
           "shiznit",
           "shota",
           "shrimping",
           "sissy",
           "skag",
           "skank",
           "skeet",
           "skullfuck",
           "slag",
           "slanteye",
           "slave",
           "sleaze",
           "sleazy",
           "slope",
           "slut",
           "slut bucket",
           "slutbag",
           "slutdumper",
           "slutkiss",
           "sluts",
           "smartass",
           "smartasses",
           "smeg",
           "smegma",
           "smut",
           "smutty",
           "snatch",
           "sniper",
           "snowballing",
           "snuff",
           "s-o-b",
           "sod off",
           "sodom",
           "sodomize",
           "sodomy",
           "son of a bitch",
           "son of a motherless goat",
           "son of a whore",
           "son-of-a-bitch",
           "souse",
           "soused",
           "spac",
           "spade",
           "sperm",
           "spic",
           "spick",
           "spik",
           "spiks",
           "splooge",
           "splooge moose",
           "spooge",
           "spook",
           "spread legs",
           "spunk",
           "steamy",
           "stfu",
           "stiffy",
           "stoned",
           "strap on",
           "strapon",
           "strappado",
           "strip",
           "strip club",
           "stroke",
           "stupid",
           "style doggy",
           "suck",
           "suckass",
           "sucked",
           "sucking",
           "sucks",
           "suicide girls",
           "sultry women",
           "sumofabiatch",
           "swastika",
           "swinger",
           "t1t",
           "t1tt1e5",
           "t1tties",
           "taff",
           "taig",
           "tainted love",
           "taking the piss",
           "tampon",
           "tard",
           "tart",
           "taste my",
           "tawdry",
           "tea bagging",
           "teabagging",
           "teat",
           "teets",
           "teez",
           "terd",
           "teste",
           "testee",
           "testes",
           "testical",
           "testicle",
           "testis",
           "threesome",
           "throating",
           "thrust",
           "thug",
           "thundercunt",
           "tied up",
           "tight white",
           "tinkle",
           "tit",
           "tit wank",
           "titfuck",
           "titi",
           "tities",
           "tits",
           "titt",
           "tittie5",
           "tittiefucker",
           "titties",
           "titty",
           "tittyfuck",
           "tittyfucker",
           "tittywank",
           "titwank",
           "toke",
           "tongue in a",
           "toots",
           "topless",
           "tosser",
           "towelhead",
           "tramp",
           "tranny",
           "transsexual",
           "trashy",
           "tribadism",
           "trumped",
           "tub girl",
           "tubgirl",
           "turd",
           "tush",
           "tushy",
           "tw4t",
           "twat",
           "twathead",
           "twatlips",
           "twats",
           "twatty",
           "twatwaffle",
           "twink",
           "twinkie",
           "two fingers",
           "two fingers with tongue",
           "two girls one cup",
           "twunt",
           "twunter",
           "ugly",
           "unclefucker",
           "undies",
           "undressing",
           "unwed",
           "upskirt",
           "urethra play",
           "urinal",
           "urine",
           "urophilia",
           "uterus",
           "uzi",
           "v14gra",
           "v1gra",
           "vag",
           "vagina",
           "vajayjay",
           "va-j-j",
           "valium",
           "venus mound",
           "veqtable",
           "viagra",
           "vibrator",
           "violet wand",
           "virgin",
           "vixen",
           "vjayjay",
           "vodka",
           "vomit",
           "vorarephilia",
           "voyeur",
           "vulgar",
           "vulva",
           "w00se",
           "wad",
           "wang",
           "wank",
           "wanker",
           "wankjob",
           "wanky",
           "wazoo",
           "wedgie",
           "weed",
           "weenie",
           "weewee",
           "weiner",
           "weirdo",
           "wench",
           "wet dream",
           "wetback",
           "wh0re",
           "wh0reface",
           "white power",
           "whitey",
           "whiz",
           "whoar",
           "whoralicious",
           "whore",
           "whorealicious",
           "whorebag",
           "whored",
           "whoreface",
           "whorehopper",
           "whorehouse",
           "whores",
           "whoring",
           "wigger",
           "willies",
           "willy",
           "window licker",
           "wiseass",
           "wiseasses",
           "wog",
           "womb",
           "woody",
           "wop",
           "wrapping men",
           "wrinkled starfish",
           "wtf",
           "xrated",
           "x-rated",
           "xx",
           "xxx",
           "yaoi",
           "yeasty",
           "yellow showers",
           "yid",
           "yiffy",
           "yobbo",
           "zoophile",
           "zoophilia",
           "zubb"
    };
}
